version: '3'
services:
    amphoto:
        container_name: amphoto
        build: .
        ports:
            - "8080:8080"
        command: bin/console server:run 0.0.0.0:8080
        tty: true
        volumes:
            - .:/var/amphoto
