version: '3'
services:
    amphoto:
        container_name: amphoto
        build: .
        ports:
            - "8080:8080"
        tty: true
        command: "symfony server:start --port 8080"
        volumes:
            - .:/var/amphoto
            - $HOME/.ssh/id_ed25519:/root/.ssh/id_ed25519:cached
