version: '3'
services:
    amphoto:
        container_name: amphoto
        build: .
        ports:
            - "8080:8080"
        command: php
        tty: true
        command: "symfony server:start --port 8080"
        volumes:
            - .:/var/amphoto
