admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    options:
        stenope: { ignore: true }

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options:
        stenope: { ignore: true }
