# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    web_content:
        class: AppBundle\Service\WebContent
    photo_category:
        class: AppBundle\Service\PhotoCategory
    wordpress_client:
        class: HieuLe\WordpressXmlrpcClient\WordpressClient
        arguments:
            - 'https://andrewmacrobertphoto.wordpress.com/xmlrpc.php'
            - '%wp_username%'
            - '%wp_password%'
