# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    web_content:
        class: AppBundle\Service\WebContent

    photo_category:
        class: AppBundle\Service\PhotoCategory

    # freebie:
    #     class: AppBundle\Service\FreebieService
    #     arguments:
    #         - '@doctrine.orm.entity_manager'
    #         - '@mailgun'

    # mailgun:
    #     class: Mailgun\Mailgun
    #     factory: ['Mailgun\Mailgun', 'create']
    #     arguments: ['%mailgun_key%']

    blog:
        class: AppBundle\Service\BlogService
        arguments:
            - '@wordpress_client'
            - '@guzzle'
            - '@cache'

    wordpress_client:
        class: HieuLe\WordpressXmlrpcClient\WordpressClient
        arguments:
            - 'https://andrewmacrobertphoto.wordpress.com/xmlrpc.php'
            - '%wp_username%'
            - '%wp_password%'

    cache:
        class: AppBundle\Service\DatabaseCacheService
        arguments: ['@doctrine.orm.entity_manager']

    guzzle:
        class: GuzzleHttp\Client
        arguments:
            defaults:
                verify: false
