# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    web_content:
        class: AppBundle\Service\WebContent

    photo_category:
        class: AppBundle\Service\PhotoCategory

    freebie:
        class: AppBundle\Service\FreebieService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@mailgun'

    mailgun:
        class: Mailgun\Mailgun
        factory: ['Mailgun\Mailgun', 'create']
        arguments: ['%mailgun_key%']

    blog:
        class: AppBundle\Service\BlogService
        arguments:
            - '@wordpress_client'
            - '@guzzle'
            - '@cache'

    wordpress_client:
        class: HieuLe\WordpressXmlrpcClient\WordpressClient
        arguments:
            - 'https://andrewmacrobertphoto.wordpress.com/xmlrpc.php'
            - '%wp_username%'
            - '%wp_password%'

    cache:
        class: AppBundle\Service\DatabaseCacheService
        arguments: ['@doctrine.orm.entity_manager']

    guzzle:
        class: GuzzleHttp\Client
        arguments:
            $config:
                verify: false

# Admins

    admin.portfolio:
        class: AppBundle\Admin\PortfolioAdmin
        arguments: [~, AppBundle\Entity\Portfolio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Portfolios, group: Entities }
        public: true

    admin.endorsement:
        class: AppBundle\Admin\EndorsementAdmin
        arguments: [~, AppBundle\Entity\Endorsement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Endorsements, group: Entities }
        public: true

    admin.freebie:
        class: AppBundle\Admin\FreebieAdmin
        arguments: [~, AppBundle\Entity\Freebie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Freebies, group: Entities }
        public: true
