AppBundle\Entity\DatabaseCacheItem:

    type: entity
    table: cache

    id: {id: {type: integer, generator: {strategy: AUTO}}}

    fields:
        key: { type: string, column: "`key`" }
        value: { type: text, column: "`value`", nullable: true }
        ttl: { type: integer, unsigned: true, nullable: true }
        date_created: { type: datetime }

    uniqueConstraints:
        key: { columns: [ key ], type: unique }

    lifecycleCallbacks:
        prePersist: [ setDateCreatedToNow ]
